portfoliosite/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('nippo/', include('nippo.urls')),
    path('', include('nippo.urls')),
]

portfoliosite/nippo/urls.py
from django.urls import path
from .views import nippoListView, nippoDetailView, nippoCreateView
from .contact import contactView
from .import views

app_name = 'nippo'
urlpatterns = [
    path("", contactView, name="nippo-contact"),
    # path("", nippoListView, name="nippo-list"),
    path("detail/<int:number>/", nippoDetailView, name="nippo-detail"),
    path("create/", nippoCreateView, name="nippo-create"),
    # path("contact/", contactView, name="nippo-contact"),
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
]

portfoliosite/nippo/models.py
from django.db import models

# Create your models here.

portfoliosite/nippo/forms.py
from django import forms
import os
from django.core.mail import EmailMessage
import environ 

env = environ.Env()
env.read_env('.env')

class NippoFormClass(forms.Form):
    title = forms.CharField()
    content = forms.CharField()

class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください。'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスを入力してください。'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルを入力してください。'
        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージを入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = env('EMAIL_HOST_USER')
        to_list = [
            env('EMAIL_HOST_USER')
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

portfoliosite/nippo/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from random import randint
from .forms import NippoFormClass, InquiryForm
from django.urls import reverse
from django.views import generic
# from django.utils import email_set
import logging
from django.urls import reverse_lazy
logger = logging.getLogger(__name__)

def nippoListView(request):
    return render(request,
                  "nippo/nippo-list.html")

def nippoDetailView(request, number):
    template_name="nippo/nippo-detail.html"
    random_int = randint(1,10)
    ctx = {
        "random_number": random_int,
        "number": number,
    }
    return render(request, template_name, ctx)


def nippoCreateView(request):
    template_name="nippo/nippo-form.html"
    form = NippoFormClass()
    ctx = {}
    ctx["form"] = form
    return render(request, template_name, ctx)

def contactView(request):
    template_name = "nippo/contact.html"
    if request.POST:
        # email_set.contactFromNippo(request.POST)
        return redirect(reverse("nippo-contact"))

    return render(request, template_name)

class IndexView(generic.TemplateView):
    template_name = "inquiry.html"
    form_class = InquiryForm

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('nippo:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)
    

portfoliosite/nippo/templates/base.html
{% load static %}

<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />

    <!-- Font Awesome icons(free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900"
        rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
        rel="stylesheet" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet" />

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
    <style>
        .navbar-brand:hover {
            background-color: dimgray;
            border-radius: 10px;
        }
    </style>
</head>

<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'nippo:nippo-contact' %}">home</a>
                <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" -->
                <!-- aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"> -->
                <!-- <span class="navbar-toggler-icon"></span></button> -->
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <!-- <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'nippo:inquiry' %}">INQUIRY</a> -->
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                    </ul>
                </div>
            </div>
        </nav>

        {% block header %}{% endblock %}

        {% if messages %}
        <div class="container my-div-style">
            <div class="row">
                <ul class="messages" style="list-style: none;">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                        {{ message }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endif %}

        {% block contents %}{% endblock %}

        <!-- Footer -->
        <footer class="py-5 bg-black">
            <div class="container px-5">
                <p class="m-0 text-center text-white small">Copyright &copy; Hiro 2023</p>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jslelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    </div>
</body>

</html>

portfoliosite/nippo/templates/contact.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'gpt.css' %}" />
    <title>Developer HIRO</title>
</head>

<body>
    <div class="home-content wrapper">
        <h2 class="page-title">
            <p>web ios App Creator</p>
            <p>Hiro</p>
        </h2>
        <h3>
            <p>I am a Japanese web and ios App Creator
                if your have any comments, please feel free to contact me!</p>
            <p>お気軽にお問い合わせください</p>
        </h3>
    </div>
    <div class="app-contents wrapper">
        <article>
            <!-- <a style="width: 170px; height: 170px; border-radius: 22%; overflow: hidden; display: inline-block; vertical-align: middle;"><img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/b9/8f/5c/b98f5c06-1eb1-8d51-c51f-23f3dbd7c1e1/AppIcon_4-1x_U007emarketing-0-6-0-85-220.png/540x540bb.jpg" alt="DAYCE" style="width: 170px; height: 170px; border-radius: 22%; overflow: hidden; display: inline-block; vertical-align: middle;"></a> -->
            <a href="https://apps.apple.com/jp/app/dayce/id6444592652?itscg=30200&amp;itsct=apps_box_appicon"
                style="width: 170px; height: 170px; border-radius: 22%; overflow: hidden; display: inline-block; vertical-align: middle;"><img
                    src="https://is4-ssl.mzstatic.com/image/thumb/Purple126/v4/ed/ca/a3/edcaa393-1ccb-e762-0adc-f4f6275ac58d/AppIcon_1-1x_U007emarketing-0-6-0-85-220.png/540x540bb.jpg"
                    alt="DAYCE"
                    style="width: 170px; height: 170px; border-radius: 22%; overflow: hidden; display: inline-block; vertical-align: middle;"></a>
            <a href="https://apps.apple.com/jp/app/dayce/id6444592652?itsct=apps_box_badge&amp;itscg=30200"
                style="display: inline-block; overflow: hidden; border-radius: 13px; width: 250px; height: 83px;"><img
                    src="https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/ja-jp?size=250x83&amp;releaseDate=1669075200"
                    alt="Download on the App Store" style="border-radius: 13px; width: 250px; height: 83px;"></a>
        </article>
        <!-- <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'nippo:inquiry' %}">お問い合わせ</a> -->
    </div>
    <div class="page-header">
        <ul class="main-nav">
            <li class="inquiry-btn"><a href="{% url 'nippo:inquiry' %}">お問い合わせ</a></li>
        </ul>
    </div>
    <footer>
        <div class="wrapper">
            <p><small>&copy; 2023 Hiro</small></p>
        </div>
    </footer>
</body>

</html>

portfoliosite/nippo/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style">
        <form method="post">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for field in form %}
            <div class="mb-4 col-8">
                <label for="{{ field.id_for_label }}" class="form-label">
                    <strong>{{ field.label_tag }}</strong>
                </label>
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">送信</button>
        </form>
    </div>
</div>
{% endblock %}

portfoliosite/nippo/templates/nippo/nippo-detail.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Views.pyからHTMLへ</title>
</head>
<body>
    <h1>
        今日のラッキーナンバーはこちら→{{random_number}}
    </h1>
    <P>
        あなたの入力した数字は→ {{ number}}
    </P>
    <p>
         {{random_number}} + {{number}} = 
         {{ random_number | add:number}}
    </p>
</body>
</html>

portfoliosite/nippo/templates/nippo/nippo-form.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>日報の作成</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">送信</button>
    </form>
</body>
</html>

portfoliosite/nippo/templates/nippo/nippo-list.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href='contact.css'>
    <title>Document</title>
</head>
<body>
    <div class="form-container">
        <div class="title">
            <h1>お問合せフォーム</h1>
        </div>
        <form method="post" action="">{% csrf_token %}
            {{ form.as_p }}
            <div class="contact-form">
                <div class="input-fields">
                    <input type="text" class="input" placeholder="名前" name="name">
                    <input type="text" class="input" placeholder="Eメールアドレス" name="email">
                </div>
                <div class="msg">
                    <textarea name="message" placeholder="メッセージ" name="message"></textarea>
                </div>
            </div>
            <button class="btn" type="submit">送信</button>
        </form>
    </div>
</body>
</html>